<!--
HelloWorld.vue - Placeholder Component for NumGame
This is a demo component generated by Vue CLI. In the actual NumGame application,
this component will be replaced with game-specific components such as GameBoard,
PlayerControls, ScoreDisplay, etc.
-->

<template>
  <!-- Main container for the demo component -->
  <div class="hello">
    <!-- Display the message prop -->
    <h1>{{ msg }}</h1>
    
    <!-- Project documentation links -->
    <p>
      For a guide and recipes on how to configure / customize this project,<br>
      check out the
      <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>.
    </p>
    
    <!-- Installed CLI plugins section -->
    <h3>Installed CLI Plugins</h3>
    <ul>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel" target="_blank" rel="noopener">babel</a></li>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint" target="_blank" rel="noopener">eslint</a></li>
    </ul>
    
    <!-- Essential Vue.js links -->
    <h3>Essential Links</h3>
    <ul>
      <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
      <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>
      <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>
      <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>
      <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>
    </ul>
    
    <!-- Vue.js ecosystem links -->
    <h3>Ecosystem</h3>
    <ul>
      <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
      <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
      <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
      <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
      <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
    </ul>
  </div>
</template>

<script>
/**
 * HelloWorld Component - Demo component for Vue CLI
 * 
 * This is a placeholder component that will be replaced with actual
 * game components in the NumGame application. It demonstrates basic
 * Vue component structure with props.
 * 
 * @module HelloWorld
 */
export default {
  // Component name used for debugging and Vue devtools
  name: 'HelloWorld',
  
  /**
   * Component props - External data passed to the component
   * 
   * @property {string} msg - The message to display in the component
   */
  props: {
    msg: String
  }
}
</script>

<!-- 
  Scoped styles - CSS limited to this component only
  The 'scoped' attribute ensures styles don't leak to other components
-->
<style scoped>
/* Heading style for h3 elements */
h3 {
  margin: 40px 0 0;
}

/* Unordered list styling */
ul {
  list-style-type: none;
  padding: 0;
}

/* List item styling */
li {
  display: inline-block;
  margin: 0 10px;
}

/* Link styling */
a {
  color: #42b983;
}
</style>
