"""change the nullability of the db

Revision ID: 532ee9997db1
Revises: 3fa7023773a6
Create Date: 2026-04-08 16:23:03.624587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532ee9997db1'
down_revision: Union[str, Sequence[str], None] = '3fa7023773a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'first_move',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('games', 'second_move',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'second_move',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('games', 'first_move',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
