"""Add first and second move sscore in games

Revision ID: 71e6b2d93d89
Revises: 3fa7023773a6
Create Date: 2026-06-09 11:04:16.393155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e6b2d93d89'
down_revision: Union[str, Sequence[str], None] = '3fa7023773a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_move_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('second_move_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'second_move_score')
    op.drop_column('games', 'first_move_score')
    # ### end Alembic commands ###
